-- Orbit local seed (supabase/config.toml -> [db.seed]). Intentionally empty:
-- the app creates its own sample data through public.seed_sample_project()
-- when a workspace is created with "Add a sample project" checked.
